# Generated by Django 4.1.1 on 2022-09-26 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='price',
            field=models.IntegerField(default=10),
        ),
    ]
